### ISSUE TITLE
[classifier] RuntimeError: The size of tensor a (19) must match the size of tensor b (2) at non-singleton dimension 1

### ISSUE THREAD

**Issue by vict0rsch** [cc-ai/omnigan#11]
Running `test_trainer.py` I get 

```
Traceback (most recent call last):
  File "test_trainer.py", line 77, in <module>
    trainer.update_g(domain_batch)
  File "../omnigan/trainer.py", line 269, in update_g
    r_loss = self.get_representation_loss(multi_domain_batch)
  File "../omnigan/trainer.py", line 334, in get_representation_loss
    prediction, update_target
  File "../omnigan/trainer.py", line 128, in <lambda>
    self.losses["G"]["tasks"]["s"] = lambda x, y: (x + y).mean()
RuntimeError: The size of tensor a (19) must match the size of tensor b (2) at non-singleton dimension 1
```

**Comment by vict0rsch** [comment]
fixed in https://github.com/cc-ai/omnigan/commit/1e4bbae44a35e56505df2a40dc58b2980bd09737
